# Generated by Django 4.2.2 on 2024-11-03 19:13

import apps.capabilities.commerce.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='currency_of_payment',
            field=models.IntegerField(choices=[(1, 'USD'), (2, 'EUR'), (3, 'GBP')], default=apps.capabilities.commerce.utils.CurrencyTypes['USD']),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'NONE'), (2, 'ONLINE'), (3, 'OFFLINE')], default=apps.capabilities.commerce.utils.PaymentTypes['ONLINE']),
        ),
    ]
