# Generated by Django 4.2.2 on 2024-11-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted'), ('test.event', 'Test Event'), ('test.multiple_listeners', 'Test Multiple Listeners')], db_index=True, help_text='Type of event from the centralized event registry', max_length=255)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delete_at', models.DateTimeField(db_index=True)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('processing_time', models.FloatField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['delete_at', 'processed'], name='event_hub_e_delete__32a99d_idx'), models.Index(fields=['event_type', 'created_at'], name='event_hub_e_event_t_e9f592_idx')],
            },
        ),
    ]
