# Generated by Django 4.2.2 on 2024-11-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='is_notification_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='parent_event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted'), ('system.notification_processing', 'Notification Processing'), ('test.event', 'Test Event'), ('test.multiple_listeners', 'Test Multiple Listeners')], db_index=True, help_text='Type of event from the centralized event registry', max_length=255),
        ),
    ]
