version: "3"

services:
  platform:
    container_name: platform
    network_mode: ${NETWORK_MODE}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - POSTGRES_HOST=pgdb
    ports:
      - 8080:80
    env_file:
      - .env
    depends_on:
      pgdb:
        condition: service_healthy
    restart: unless-stopped

  pgdb:
    container_name: pgdb
    network_mode: ${NETWORK_MODE}
    image: postgres:12
    restart: unless-stopped
    volumes:
      - type: volume
        source: pgdb-data
        target: "/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBUSER}"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  pgdb-data:
