# Generated by Django 4.2.2 on 2024-11-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0014_delete_status'),
        ('commerce', '0002_initial'),
        ('product_management', '0051_remove_challenge_tag_delete_tag'),
        ('security', '0010_alter_productroleassignment_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationPersonRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager'), ('Member', 'Member')], default='Member', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='productroleassignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_roles', to='talent.person'),
        ),
        migrations.AlterField(
            model_name='productroleassignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='product_management.product'),
        ),
        migrations.AlterField(
            model_name='productroleassignment',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='Member', max_length=255),
        ),
        migrations.AddIndex(
            model_name='productroleassignment',
            index=models.Index(fields=['person', 'product', 'role'], name='security_pr_person__833637_idx'),
        ),
        migrations.AddField(
            model_name='organisationpersonroleassignment',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_role_assignments', to='commerce.organisation'),
        ),
        migrations.AddField(
            model_name='organisationpersonroleassignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_roles', to='talent.person'),
        ),
        migrations.AddIndex(
            model_name='organisationpersonroleassignment',
            index=models.Index(fields=['person', 'organisation', 'role'], name='security_or_person__91dda4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationpersonroleassignment',
            unique_together={('person', 'organisation')},
        ),
    ]
