# Generated by Django 4.2.2 on 2023-08-02 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0003_idea"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductRole",
        ),
    ]
