# Generated by Django 4.2.2 on 2023-08-14 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0004_product_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChallengeListing",
        ),
    ]
