# Generated by Django 4.2.2 on 2023-09-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0005_delete_challengelisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="vote_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
