# Generated by Django 4.2.2 on 2023-09-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0006_idea_created_at_idea_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="website",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
