# Generated by Django 4.2.2 on 2023-09-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0010_person_completed_profile"),
        ("product_management", "0007_alter_product_photo_alter_product_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="expertise",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="bounty",
            name="skill",
        ),
        migrations.AddField(
            model_name="bounty",
            name="skill",
            field=models.ManyToManyField(
                related_name="bounty_skill", to="talent.skill"
            ),
        ),
    ]
