# Generated by Django 4.2.2 on 2023-09-22 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0007_alter_product_photo_alter_product_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="expertise",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="skill_mode",
        ),
    ]
