# Generated by Django 4.2.2 on 2023-11-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0008_alter_challenge_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bounty",
            name="points",
            field=models.PositiveIntegerField(),
        ),
    ]
