# Generated by Django 4.2.2 on 2023-11-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0009_alter_bounty_points"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={},
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="file_type",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="name",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="path",
        ),
        migrations.AddField(
            model_name="attachment",
            name="file",
            field=models.FileField(default=None, upload_to="attachments"),
            preserve_default=False,
        ),
    ]
