# Generated by Django 4.2.2 on 2024-03-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product_management",
            "0011_capability_video_duration_capability_video_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="capability",
            name="description",
            field=models.TextField(default="", max_length=1000, null=True),
        ),
    ]
