# Generated by Django 4.2.2 on 2024-03-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0012_alter_capability_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capability",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=1000, null=True
            ),
        ),
    ]
