# Generated by Django 4.2.2 on 2024-03-23 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0003_alter_bountyclaim_kind"),
        ("product_management", "0013_alter_capability_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Capability",
            new_name="ProductArea",
        ),
        migrations.RemoveField(
            model_name="product",
            name="capability_start",
        ),
        migrations.AlterModelTable(
            name="productarea",
            table=None,
        ),
    ]
