# Generated by Django 4.2.2 on 2024-03-24 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "product_management",
            "0016_alter_productarea_options_alter_producttree_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttree",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
