# Generated by Django 4.2.2 on 2024-03-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product_management",
            "0019_alter_productareaattachment_product_area",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productareaattachment",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="attachments"
            ),
        ),
    ]
