# Generated by Django 4.2.2 on 2024-03-30 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0020_productareaattachment_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productareaattachment",
            name="attachment",
        ),
    ]
