# Generated by Django 4.2.2 on 2024-04-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0021_bounty_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BountyAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("file", models.FileField(upload_to="attachments")),
                (
                    "title",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "bounty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bounties",
                        to="product_management.bounty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
