# Generated by Django 4.2.2 on 2024-04-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0021_bountyattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
