# Generated by Django 4.2.2 on 2024-03-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0021_remove_productareaattachment_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productareaattachment",
            name="file",
            field=models.FileField(default=1, upload_to="attachments"),
            preserve_default=False,
        ),
    ]
