# Generated by Django 4.2.2 on 2024-04-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0022_alter_productareaattachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="productareaattachment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productareaattachment",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
