# Generated by Django 4.2.2 on 2024-04-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0022_bountyattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="title",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
