# Generated by Django 4.2.2 on 2024-05-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0025_remove_challenge_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="voted_users",
            field=models.JSONField(default=list),
        ),
    ]
