# Generated by Django 4.2.2 on 2024-05-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_management",
            "0026_rename_capability_challenge_product_area",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bounty",
            options={"ordering": ("-created_at",)},
        ),
    ]
