# Generated by Django 4.2.2 on 2024-05-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0027_alter_bounty_options"),
        ("product_management", "0027_remove_idea_vote_count"),
    ]

    operations = []
