# Generated by Django 4.2.2 on 2024-05-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ("product_management", "0028_merge_20240513_1342"),
        ("product_management", "0029_ideavote"),
        ("product_management", "0030_delete_ideavote"),
        ("product_management", "0031_remove_idea_voted_users"),
    ]

    dependencies = [
        ("talent", "0006_remove_bountyclaim_kind_bountyclaim_status"),
        ("product_management", "0027_alter_bounty_options"),
        ("product_management", "0027_remove_idea_vote_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idea",
            name="voted_users",
        ),
    ]
