# Generated by Django 4.2.2 on 2024-05-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0029_ideavote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IdeaVote",
        ),
    ]
