# Generated by Django 4.2.2 on 2024-05-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0030_delete_ideavote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idea",
            name="voted_users",
        ),
    ]
