# Generated by Django 4.2.2 on 2024-05-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0028_bounty_claimed_by"),
        ("product_management", "0031_remove_idea_voted_users"),
    ]

    operations = []
