# Generated by Django 4.2.2 on 2024-05-20 15:08

from django.db import migrations, models
from product_management.models import Bounty as NewBounty


def forward_func(apps, schema_editor):
    Bounty = apps.get_model("product_management", "Bounty")

    # Update the status values
    status_mapping = {
        2: NewBounty.BountyStatus.AVAILABLE,
        3: NewBounty.BountyStatus.CLAIMED,
        4: NewBounty.BountyStatus.COMPLETED,
        5: NewBounty.BountyStatus.IN_REVIEW,
    }
    migrate_ids = [2, 3, 4, 5]

    for bounty in Bounty.objects.filter(status__in=migrate_ids):
        bounty.status = status_mapping.get(bounty.status, bounty.status)
        bounty.save()

    Bounty.objects.exclude(status__in=migrate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0032_merge_20240515_0713"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bounty",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Claimed", "Claimed"),
                    ("In Review", "In Review"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Available",
                max_length=255,
            ),
        ),
        migrations.RunPython(forward_func, migrations.RunPython.noop),
    ]
