# Generated by Django 4.2.2 on 2024-05-20 19:26
from product_management.models import Challenge as NewChallenge
from django.db import migrations, models


def forward_func(apps, schema_editor):
    Challenge = apps.get_model("product_management", "Challenge")

    # Update the status values
    status_mapping = {
        0: NewChallenge.ChallengeStatus.DRAFT,
        1: NewChallenge.ChallengeStatus.BLOCKED,
        2: NewChallenge.ChallengeStatus.ACTIVE,
        4: NewChallenge.ChallengeStatus.COMPLETED,
    }

    migrate_ids = [0, 1, 2, 4]

    for challenge in Challenge.objects.filter(status__in=migrate_ids):
        challenge.status = status_mapping.get(
            challenge.status, challenge.status
        )
        challenge.save()

    Challenge.objects.exclude(status__in=migrate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0033_alter_bounty_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Blocked", "Blocked"),
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Draft",
                max_length=255,
            ),
        ),
        migrations.RunPython(forward_func, migrations.RunPython.noop),
    ]
