# Generated by Django 4.2.2 on 2024-05-21 22:51

from django.db import migrations, models
from product_management.models import Initiative as NewInitiative


def forward_func(apps, schema_editor):
    Initiative = apps.get_model("product_management", "Initiative")

    status_mapping = {
        1: NewInitiative.InitiativeStatus.ACTIVE,
        2: NewInitiative.InitiativeStatus.COMPLETED,
        3: NewInitiative.InitiativeStatus.DRAFT,
        4: NewInitiative.InitiativeStatus.CANCELLED,
    }

    migrate_ids = [1, 2, 3, 4]
    for initiative in Initiative.objects.filter(status__in=migrate_ids):
        initiative.status = status_mapping.get(
            initiative.status, initiative.status
        )
        initiative.save()


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0034_alter_challenge_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiative",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Active",
                max_length=255,
            ),
        ),
        migrations.RunPython(forward_func, migrations.RunPython.noop),
    ]
