# Generated by Django 4.2.2 on 2024-05-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0033_contributionagreement"),
        ("product_management", "0035_alter_initiative_status"),
    ]

    operations = []
