# Generated by Django 4.2.2 on 2024-05-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0036_merge_20240522_0830"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="attachments")),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ProductAreaAttachment",
        ),
        migrations.AddField(
            model_name="productarea",
            name="attachments",
            field=models.ManyToManyField(null=True, to="product_management.fileattachment"),
        ),
    ]
