# Generated by Django 4.2.2 on 2024-05-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0038_alter_productarea_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="product_management.fileattachment"),
        ),
    ]
