# Generated by Django 4.2.2 on 2024-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0041_remove_fileattachment_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="product_management.fileattachment"),
        ),
        migrations.DeleteModel(
            name="BountyAttachment",
        ),
    ]
