# Generated by Django 4.2.2 on 2024-05-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0042_bounty_attachments_delete_bountyattachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="attachment",
        ),
        migrations.AddField(
            model_name="product",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="product_management.fileattachment"),
        ),
    ]
