# Generated by Django 4.2.2 on 2024-11-23 14:50

import apps.engagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_appnotification_appnotificationtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailnotificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notifiableevent',
            name='delete_at',
            field=models.DateTimeField(default=apps.engagement.models.default_delete_at),
        ),
        migrations.AlterField(
            model_name='notifiableevent',
            name='event_type',
            field=models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted')], db_index=True, max_length=50),
        ),
    ]
