# Generated by Django 4.2.2 on 2024-11-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_alter_appnotificationtemplate_event_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appnotificationtemplate',
            old_name='message_template',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='appnotificationtemplate',
            old_name='title_template',
            new_name='title',
        ),
    ]
