# Generated by Django 4.2.2 on 2024-11-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_alter_appnotificationtemplate_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted'), ('system.notification_processing', 'Notification Processing'), ('test.event', 'Test Event'), ('test.multiple_listeners', 'Test Multiple Listeners')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailnotificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted'), ('system.notification_processing', 'Notification Processing'), ('test.event', 'Test Event'), ('test.multiple_listeners', 'Test Multiple Listeners')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notifiableevent',
            name='event_type',
            field=models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted'), ('system.notification_processing', 'Notification Processing'), ('test.event', 'Test Event'), ('test.multiple_listeners', 'Test Multiple Listeners')], db_index=True, max_length=50),
        ),
    ]
