# Generated by Django 4.2.2 on 2024-11-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0006_alter_appnotificationtemplate_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifiableevent',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
