# Generated by Django 4.2.2 on 2024-11-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0017_alter_bountyclaim_options_and_more'),
        ('engagement', '0008_remove_notifiableevent_processed_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appnotification',
            name='engagement__event_i_5298f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailnotification',
            name='engagement__event_i_350a65_idx',
        ),
        migrations.RemoveField(
            model_name='appnotification',
            name='event',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='event',
        ),
        migrations.AddField(
            model_name='appnotification',
            name='notifiable_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to='engagement.notifiableevent'),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to='talent.person'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='notifiable_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='engagement.notifiableevent'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='talent.person'),
        ),
        migrations.AddIndex(
            model_name='appnotification',
            index=models.Index(fields=['notifiable_event'], name='engagement__notifia_302b57_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['notifiable_event'], name='engagement__notifia_25331a_idx'),
        ),
    ]
