# Generated by Django 4.2.2 on 2024-05-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0007_remove_ideavote_voted_at_ideavote_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IdeaVote",
        ),
    ]
