# Generated by Django 4.2.2 on 2024-06-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0009_alter_productroleassignment_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productroleassignment",
            name="role",
            field=models.CharField(
                choices=[("Contributor", "Contributor"), ("Manager", "Manager"), ("Admin", "Admin")],
                default="Contributor",
                max_length=255,
            ),
        ),
    ]
