# Generated by Django 4.2.2 on 2024-11-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_update_product_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
