# Generated by Django 4.2.2 on 2024-11-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedusernames',
            options={'verbose_name': 'Blacklisted Username', 'verbose_name_plural': 'Blacklisted Usernames'},
        ),
        migrations.AlterModelOptions(
            name='organisationpersonroleassignment',
            options={'verbose_name_plural': 'Org Role Assignments'},
        ),
        migrations.AlterModelOptions(
            name='productroleassignment',
            options={'verbose_name_plural': 'Product Role Assignments'},
        ),
        migrations.AlterModelOptions(
            name='signinattempt',
            options={'verbose_name_plural': 'Sign In Attempts'},
        ),
        migrations.AlterModelOptions(
            name='signuprequest',
            options={'verbose_name_plural': 'Sign Up Requests'},
        ),
    ]
