# Generated by Django 4.2.2 on 2024-05-21 22:51

from django.db import migrations, models


def forward_func(apps, schema_editor):
    Initiative = apps.capabilities.get_model("product_management", "Initiative")
    for initiative in Initiative.objects.all():
        status = int(initiative.status)
        if status == 1:
            initiative.status = "Active"
        elif status == 2:
            initiative.status = "Completed"
        elif status == 3:
            initiative.status = "Draft"
        elif status == 4:
            initiative.status == "Cancelled"
        initiative.save()


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0034_alter_challenge_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiative",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Active",
                max_length=255,
            ),
        ),
        migrations.RunPython(forward_func, migrations.RunPython.noop),
    ]
