# Generated by Django 4.2.2 on 2024-05-27 17:05

from django.db import migrations, models

LIQUID_POINTS = "Liquid Points"
NON_LIQUID_POINTS = "Non-liquid Points"

HIGH = "High"
MEDIUM = "Medium"
LOW = "Low"


def forward_fun(apps, schema_editor):
    Challenge = apps.get_model("product_management", "Challenge")
    for challenge in Challenge.objects.all():
        if challenge.priority in [0, "0"]:
            challenge.priority = HIGH
        elif challenge.priority == [1, "1"]:
            challenge.priority = MEDIUM
        elif challenge.priority == [2, "2"]:
            challenge.priority = LOW

        if challenge.reward_type == [0, "0"]:
            challenge.reward_type = LIQUID_POINTS
        elif challenge.reward_type == [1, "1"]:
            challenge.reward_type = NON_LIQUID_POINTS

        challenge.save()


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0043_remove_product_attachment_product_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="priority",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")], default="High", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="reward_type",
            field=models.CharField(
                choices=[("Liquid Points", "Liquid Points"), ("Non-liquid Points", "Non Liquid Points")],
                default="Non-liquid Points",
                max_length=50,
            ),
        ),
        migrations.RunPython(forward_fun, migrations.RunPython.noop),
    ]
