# Generated by Django 4.2.2 on 2024-06-03 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0046_productcontributoragreementtemplate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttree",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="producttree",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="producttree",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="producttree",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="producttree",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="producttree",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_trees",
                to="product_management.product",
            ),
        ),
    ]
