# Generated by Django 4.2.2 on 2024-06-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0047_alter_producttree_options_producttree_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productarea",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="productarea",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
