# Generated by Django 4.2.2 on 2024-06-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0048_productarea_created_at_productarea_updated_at"),
        ("product_management", "0048_productcontributoragreement_and_more"),
    ]

    operations = []
