# Generated by Django 4.2.2 on 2024-06-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0014_delete_status"),
        ("product_management", "0049_merge_20240614_0819"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcontributoragreement",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="contributor_agreement", to="talent.person"
            ),
        ),
        migrations.AlterField(
            model_name="productcontributoragreementtemplate",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributor_agreement_templates",
                to="product_management.product",
            ),
        ),
    ]
