# Generated by Django 4.2.2 on 2024-11-01 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0014_delete_status'),
        ('commerce', '0002_initial'),
        ('product_management', '0052_product_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="object_id",
        ),
        migrations.AddField(
            model_name="product",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_products",
                to="commerce.organisation",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_products",
                to="talent.person",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="product_man_slug_74fe12_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["organisation"], name="product_man_organis_d3e00b_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["person"], name="product_man_person__714b9f_idx"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("organisation__isnull", False), ("person__isnull", True)),
                    models.Q(("organisation__isnull", True), ("person__isnull", False)),
                    _connector="OR",
                ),
                name="product_single_owner",
            ),
        ),
    ]
