# Generated by Django 4.2.2 on 2024-11-01 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0054_fix_product_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_private',
            field=models.BooleanField(default=False),
        )
    ]
