# Generated by Django 4.2.2 on 2024-11-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0056_alter_initiative_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='product_management.product'),
        ),
    ]
