# Generated by Django 4.2.2 on 2024-11-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0058_product_product_man_slug_74fe12_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_private',
        ),
    ]
