# Generated by Django 4.2.2 on 2024-04-18 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0004_alter_bountyclaim_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bountyclaim",
            options={"ordering": ("-created_at",)},
        ),
    ]
