# Generated by Django 4.2.2 on 2024-05-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0045_ideavote_delete_attachment"),
        ("talent", "0011_alter_bountydeliveryattempt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bountydeliveryattempt",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="product_management.fileattachment"),
        ),
        migrations.DeleteModel(
            name="PersonWebsite",
        ),
    ]
