# Generated by Django 4.2.2 on 2024-11-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0016_fix_bountydeliveryattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bountyclaim',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Bounty Claims'},
        ),
        migrations.AlterModelOptions(
            name='bountydeliveryattempt',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Product Delivery Attempts'},
        ),
        migrations.AlterModelOptions(
            name='personskill',
            options={'verbose_name_plural': 'Person Skills'},
        ),
        migrations.AlterField(
            model_name='bountyclaim',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bounty_claims', to='talent.person'),
        ),
        migrations.AlterField(
            model_name='bountydeliveryattempt',
            name='kind',
            field=models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to='talent.person'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='talent.person'),
        ),
    ]
