# Generated by Django 4.2.2 on 2024-05-28 21:01

from django.db import migrations, models


def forward_func(apps, schema):
    productFileAttachment = apps.get_model("product_management.FileAttachment")
    commonFileAttachment = apps.get_model("common.FileAttachment")

    for attachment in productFileAttachment.objects.all():
        commonFileAttachment.objects.create(id=attachment.id, file=attachment.file)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="attachments")),
            ],
        ),
        migrations.RunPython(forward_func),
    ]
