# Generated by Django 4.2.2 on 2023-10-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="full_description",
            field=models.TextField(),
        ),
    ]
