# Generated by Django 4.2.2 on 2023-10-31 13:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0005_alter_product_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
