# Generated by Django 4.2.2 on 2024-03-24 21:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0015_producttree_productarea_product_tree"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productarea",
            options={},
        ),
        migrations.AlterField(
            model_name="producttree",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b070549e-8a1a-4ad9-a5e9-8d4f3cdfeddd"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
