# Generated by Django 4.2.2 on 2024-03-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0017_alter_producttree_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAreaAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_management.attachment",
                    ),
                ),
                (
                    "product_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_management.productarea",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CapabilityAttachment",
        ),
    ]
