# Generated by Django 4.2.2 on 2024-03-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product_management",
            "0019_alter_productareaattachment_product_area",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productareaattachment",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="attachments"
            ),
        ),
        migrations.RemoveField(
            model_name="productareaattachment",
            name="attachment",
        ),
        migrations.AlterField(
            model_name="productareaattachment",
            name="file",
            field=models.FileField(default=1, upload_to="attachments"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productareaattachment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productareaattachment",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
