# Generated by Django 4.2.2 on 2024-04-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0020_productareaattachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
