# Generated by Django 4.2.2 on 2024-05-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0025_remove_challenge_reviewer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challenge",
            old_name="capability",
            new_name="product_area",
        ),
    ]
