# Generated by Django 4.2.2 on 2024-05-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0006_remove_bountyclaim_kind_bountyclaim_status"),
        ("product_management", "0027_alter_bounty_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bounty_claimed_by",
                to="talent.person",
            ),
        ),
    ]
