# Generated by Django 4.2.2 on 2024-05-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0037_fileattachment_delete_productareaattachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productarea",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="product_management.fileattachment"),
        ),
    ]
