# Generated by Django 4.2.2 on 2024-05-30 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product_management", "0044_alter_challenge_priority_alter_challenge_reward_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdeaVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("idea", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="product_management.idea")),
                ("voter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("voter", "idea")},
            },
        ),
        migrations.DeleteModel(
            name="Attachment",
        ),
    ]
