# Generated by Django 4.2.2 on 2024-05-31 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0012_alter_bountydeliveryattempt_attachments_and_more"),
        ("product_management", "0045_ideavote_delete_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductContributorAgreementTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=256)),
                ("content", models.TextField()),
                ("effective_date", models.DateField()),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="talent.person")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_contribution_agreements",
                        to="product_management.product",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.DeleteModel(
            name="ContributionAgreement",
        ),
    ]
