# Generated by Django 4.2.2 on 2024-06-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0014_delete_status"),
        ("product_management", "0047_alter_producttree_options_producttree_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductContributorAgreement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("accepted_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="contributoragreementacceptance",
            name="agreement",
        ),
        migrations.RemoveField(
            model_name="contributoragreementacceptance",
            name="person",
        ),
        migrations.AlterField(
            model_name="productcontributoragreementtemplate",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_contributor_agreements",
                to="product_management.product",
            ),
        ),
        migrations.DeleteModel(
            name="ContributorAgreement",
        ),
        migrations.DeleteModel(
            name="ContributorAgreementAcceptance",
        ),
        migrations.AddField(
            model_name="productcontributoragreement",
            name="agreement_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="product_management.productcontributoragreementtemplate",
            ),
        ),
        migrations.AddField(
            model_name="productcontributoragreement",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_contributor_agreement",
                to="talent.person",
            ),
        ),
    ]
