# Generated by Django 4.2.2 on 2024-05-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0049_alter_bounty_attachments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileAttachment",
        ),
    ]
