# Generated by Django 4.2.2 on 2024-06-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0050_alter_productcontributoragreement_person_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="tag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
