# Generated by Django 4.2.2 on 2024-07-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0051_remove_challenge_tag_delete_tag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductChallenge",
        ),
    ]
