# Generated by Django 4.2.2 on 2024-11-02 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0055_product_is_private_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='product_management.product'),
        ),
    ]
