# Generated by Django 4.2.2 on 2023-07-14 18:16

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_logged', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(default='', max_length=39, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username may only contain letters and numbers', regex='^[a-z0-9]*$')])),
            ],
            options={
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='BlacklistedUsernames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'black_listed_usernames',
            },
        ),
    ]
