# Generated by Django 4.2.2 on 2023-07-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0001_initial'),
        ('commerce', '0002_initial'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productowner',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
        ),
        migrations.AddField(
            model_name='organisationperson',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.organisation'),
        ),
        migrations.AddField(
            model_name='organisationperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
        ),
    ]
