# Generated by Django 4.2.2 on 2023-08-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="remaining_budget_for_failed_logins",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
