# Generated by Django 4.2.2 on 2023-07-28 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
