# Generated by Django 4.2.2 on 2023-07-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
