# Generated by Django 4.2.2 on 2023-10-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0003_alter_productroleassignment_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signuprequest",
            name="successful",
            field=models.BooleanField(default=False),
        ),
    ]
