# Generated by Django 4.2.2 on 2023-08-14 08:07

from django.db import migrations, models
import security.managers


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0003_user_password_reset_required_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignInAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("device_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("country", models.CharField(blank=True, max_length=64, null=True)),
                ("region_code", models.CharField(blank=True, max_length=8, null=True)),
                ("city", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", security.managers.UserManager()),
            ],
        ),
    ]
