# Generated by Django 4.2.2 on 2023-07-21 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="",
                max_length=39,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username may only contain letters and numbers without any spaces",
                        regex="^[a-z0-9]*$",
                    )
                ],
            ),
        ),
    ]
