# Generated by Django 4.2.2 on 2023-08-14 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0003_remove_product_owner"),
        ("security", "0004_signinattempt_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="signinattempt",
            name="successful",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="signinattempt",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productperson",
            name="role",
            field=models.IntegerField(
                choices=[(1, "Contributor"), (2, "Manager"), (3, "Admin")], default=0
            ),
        ),
        migrations.DeleteModel(
            name="ProductOwner",
        ),
    ]
