# Generated by Django 4.2.2 on 2023-08-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0005_signinattempt_successful_signinattempt_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productperson",
            name="role",
            field=models.IntegerField(
                choices=[(0, "Contributor"), (1, "Manager"), (2, "Admin")], default=0
            ),
        ),
    ]
