# Generated by Django 4.2.2 on 2023-08-14 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0001_initial"),
        ("security", "0006_alter_productperson_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "Contributor"), (1, "Manager"), (2, "Admin")],
                        default=0,
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="talent.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ProductPerson",
        ),
    ]
