# Generated by Django 4.2.2 on 2023-08-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0006_signuprequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verification_code", models.CharField(max_length=6)),
            ],
        ),
    ]
