# Generated by Django 4.2.2 on 2023-08-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0007_productroleassignment_delete_productperson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signuprequest",
            name="email",
        ),
        migrations.RemoveField(
            model_name="signuprequest",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="signuprequest",
            name="password",
        ),
        migrations.RemoveField(
            model_name="signuprequest",
            name="preferred_name",
        ),
        migrations.RemoveField(
            model_name="signuprequest",
            name="username",
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferred_name",
        ),
        migrations.AddField(
            model_name="signuprequest",
            name="city",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="signuprequest",
            name="country",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="signuprequest",
            name="device_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="signuprequest",
            name="region_code",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="signuprequest",
            name="successful",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_test_user",
            field=models.BooleanField(default=False, verbose_name="Test User"),
        ),
    ]
