# Generated by Django 4.2.2 on 2023-08-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0005_delete_challengelisting"),
        ("security", "0008_remove_signuprequest_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productroleassignment",
            name="product",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="product_management.product",
            ),
        ),
    ]
