# Generated by Django 4.2.2 on 2023-10-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bountydeliveryattempt",
            name="bounty_claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_attempt",
                to="talent.bountyclaim",
            ),
        ),
        migrations.AlterField(
            model_name="bountydeliveryattempt",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="talent.person"
            ),
        ),
    ]
