# Generated by Django 4.2.2 on 2023-07-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BountyDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "kind",
                    models.IntegerField(
                        choices=[(0, "New"), (1, "Approved"), (2, "Rejected")],
                        default=0,
                    ),
                ),
                ("is_canceled", models.BooleanField(default=False)),
                ("delivery_message", models.CharField(default=None, max_length=2000)),
                (
                    "bounty_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempt",
                        to="talent.bountyclaim",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talent.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BountyDeliveryAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_type", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=100)),
                (
                    "bounty_delivery_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="talent.bountydeliveryattempt",
                    ),
                ),
            ],
        ),
    ]
