# Generated by Django 4.2.2 on 2023-08-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="is_test_user",
        ),
        migrations.AddField(
            model_name="person",
            name="full_name",
            field=models.CharField(default="blank", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="preferred_name",
            field=models.CharField(default="blank preferred_name", max_length=128),
            preserve_default=False,
        ),
    ]
