# Generated by Django 4.2.2 on 2023-07-22 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="talent",
            table="talent_talent",
        ),
    ]
