# Generated by Django 4.2.2 on 2023-08-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="linkedin_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="twitter_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
