# Generated by Django 4.2.2 on 2023-08-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0002_remove_person_is_test_user_person_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="website_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="twitter_link",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
