# Generated by Django 5.1.dev20240226155703 on 2024-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0002_bountydeliveryattempt_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bountyclaim",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (0, "Done"),
                    (1, "Active"),
                    (2, "Failed"),
                    (3, "In review"),
                ],
                default=3,
            ),
        ),
    ]
