# Generated by Django 4.2.2 on 2024-04-17 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0022_bountyattachment"),
        ("talent", "0003_alter_bountyclaim_kind"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bountyclaim",
            unique_together={("bounty", "person")},
        ),
    ]
