# Generated by Django 4.2.2 on 2024-04-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0004_remove_bountyclaim_kind_bountyclaim_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bountyclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("Requested", "Requested"),
                    ("Rejected", "Rejected"),
                    ("Granted", "Granted"),
                    ("Contributed", "Contributed"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                default="Requested",
                max_length=255,
            ),
        ),
    ]
