# Generated by Django 4.2.2 on 2024-04-27 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0005_alter_bountyclaim_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bountyclaim",
            old_name="kind",
            new_name="status",
        ),
    ]
