# Generated by Django 4.2.2 on 2023-08-22 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0005_skill_display_boost_factor"),
        ("talent", "0005_status"),
    ]

    operations = []
