# Generated by Django 4.2.2 on 2023-08-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0006_merge_0005_skill_display_boost_factor_0005_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="location",
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
