# Generated by Django 4.2.2 on 2024-05-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0007_remove_personskill_expertise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertise",
            name="fa_icon",
            field=models.CharField(default="fa fa-trash", max_length=100),
            preserve_default=False,
        ),
    ]
