# Generated by Django 4.2.2 on 2024-05-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("talent", "0012_delete_personwebsite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bountydeliveryattempt",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="common.fileattachment"),
        ),
    ]
