# Generated by Django 4.2.2 on 2024-05-31 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0013_person_points"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Status",
        ),
    ]
