name: Deploy to Production and Demo

concurrency: deploy_to_production

on:
  - workflow_dispatch

env:
  STAGING_ID: cc67ac7f-d41b-4a9c-a2ce-37f322690cb8
  PRODUCTION_ID: c3364f4f-1d34-4b31-ac49-da9782159a7e
  DEMO_ID: c87ff841-b900-4cc7-b3ea-19d29948be6e

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install yq
    - name: Fetch spec files
      run: |
        doctl apps spec get $STAGING_ID > staging.yaml
        doctl apps spec get $PRODUCTION_ID > production.yaml
        doctl apps spec get $DEMO_ID > demo.yaml
    - name: Update image tag and env vars
      run: |
        export TAG="$(python -m yq -r '.services[] | select(.name == "platform") | .image.tag' staging.yaml)"
        echo "Updating production image tag to $TAG"
        # Update tags
        python -m yq -Y --indentless --arg TAG "$TAG" '.services[].image.tag = $TAG' production.yaml > tmp.yaml && mv tmp.yaml production.yaml
        python -m yq -Y --indentless --arg TAG "$TAG" '.services[].image.tag = $TAG' demo.yaml > tmp.yaml && mv tmp.yaml demo.yaml
    - name: Update the environments
      run: |
        doctl apps update $PRODUCTION_ID --spec production.yaml
        doctl apps update $DEMO_ID --spec demo.yaml
        
    - name: Wait for deployment
      run: sleep 30
      
    - name: Check production deployment
      run: |
        echo "Production worker logs:"
        doctl apps logs $PRODUCTION_ID django-q-worker --tail 50
        echo "Production platform logs:"
        doctl apps logs $PRODUCTION_ID platform --tail 50
        
    - name: Check demo deployment
      run: |
        echo "Demo worker logs:"
        doctl apps logs $DEMO_ID django-q-worker --tail 50
        echo "Demo platform logs:"
        doctl apps logs $DEMO_ID platform --tail 50