name: Deploy to Production and Demo

concurrency: deploy_to_production

on:
  - workflow_dispatch

env:
  STAGING_ID: cc67ac7f-d41b-4a9c-a2ce-37f322690cb8
  PRODUCTION_ID: c3364f4f-1d34-4b31-ac49-da9782159a7e
  DEMO_ID: c87ff841-b900-4cc7-b3ea-19d29948be6e

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install yq
    - name: Fetch spec files
      run: |
        doctl apps spec get $STAGING_ID > staging.yaml
        doctl apps spec get $PRODUCTION_ID > production.yaml
        doctl apps spec get $DEMO_ID > demo.yaml
    - name: Verify image exists
      run: |
        export TAG="$(python -m yq -r '.services[] | select(.name == "platform") | .image.tag' staging.yaml)"
        if ! doctl registry repository list-tags openunited/core --format Tag | grep -q "^$TAG$"; then
          echo "Image tag $TAG not found in registry"
          exit 1
        fi
    - name: Update image tag and env vars
      run: |
        export TAG="$(python -m yq -r '.services[] | select(.name == "platform") | .image.tag' staging.yaml)"
        if [ -z "$TAG" ]; then
          echo "Failed to get tag from staging environment"
          exit 1
        fi
        echo "Updating production and demo image tags to $TAG"
        
        # Update production tags
        python -m yq -Y --indentless --arg TAG "$TAG" '.services[].image.tag = $TAG' production.yaml > tmp.yaml && mv tmp.yaml production.yaml
        python -m yq -Y --indentless --arg TAG "$TAG" '.workers[].image.tag = $TAG' production.yaml > tmp.yaml && mv tmp.yaml production.yaml
        
        # Update demo tags
        python -m yq -Y --indentless --arg TAG "$TAG" '.services[].image.tag = $TAG' demo.yaml > tmp.yaml && mv tmp.yaml demo.yaml
        python -m yq -Y --indentless --arg TAG "$TAG" '.workers[].image.tag = $TAG' demo.yaml > tmp.yaml && mv tmp.yaml demo.yaml
        
        # Verify the updates
        PROD_TAG=$(python -m yq -r '.services[] | select(.name == "platform") | .image.tag' production.yaml)
        PROD_WORKER_TAG=$(python -m yq -r '.workers[] | select(.name == "django-q-worker") | .image.tag' production.yaml)
        DEMO_TAG=$(python -m yq -r '.services[] | select(.name == "platform") | .image.tag' demo.yaml)
        DEMO_WORKER_TAG=$(python -m yq -r '.workers[] | select(.name == "django-q-worker") | .image.tag' demo.yaml)
        
        if [ "$TAG" != "$PROD_TAG" ] || [ "$TAG" != "$PROD_WORKER_TAG" ] || [ "$TAG" != "$DEMO_TAG" ] || [ "$TAG" != "$DEMO_WORKER_TAG" ]; then
          echo "Tag update verification failed"
          exit 1
        fi
    - name: Update the environments
      run: |
        doctl apps update $PRODUCTION_ID --spec production.yaml
        doctl apps update $DEMO_ID --spec demo.yaml
        
    - name: Wait for production deployment
      run: |
        echo "Waiting for production deployment to complete..."
        while true; do
          STATUS=$(doctl apps get $PRODUCTION_ID --format Status --no-header)
          if [ "$STATUS" = "running" ]; then
            echo "Production deployment complete!"
            break
          elif [ "$STATUS" = "error" ]; then
            echo "Production deployment failed!"
            exit 1
          fi
          echo "Status: $STATUS - waiting 30 seconds..."
          sleep 30
        done

    - name: Wait for demo deployment
      run: |
        echo "Waiting for demo deployment to complete..."
        while true; do
          STATUS=$(doctl apps get $DEMO_ID --format Status --no-header)
          if [ "$STATUS" = "running" ]; then
            echo "Demo deployment complete!"
            break
          elif [ "$STATUS" = "error" ]; then
            echo "Demo deployment failed!"
            exit 1
          fi
          echo "Status: $STATUS - waiting 30 seconds..."
          sleep 30
        done
        
    - name: Check production deployment
      run: |
        echo "Production worker logs:"
        doctl apps logs $PRODUCTION_ID django-q-worker --tail 50
        echo "Production platform logs:"
        doctl apps logs $PRODUCTION_ID platform --tail 50
        
    - name: Check demo deployment
      run: |
        echo "Demo worker logs:"
        doctl apps logs $DEMO_ID django-q-worker --tail 50
        echo "Demo platform logs:"
        doctl apps logs $DEMO_ID platform --tail 50