name: Deploy to Production and Demo

concurrency: deploy_to_production

on:
  - workflow_dispatch

env:
  PRODUCTION_ID: c3364f4f-1d34-4b31-ac49-da9782159a7e
  DEMO_ID: c87ff841-b900-4cc7-b3ea-19d29948be6e

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
    - run: pip install yq
    - name: Fetch spec files
      run: |
        doctl apps spec get $PRODUCTION_ID > production.yaml
        doctl apps spec get $DEMO_ID > demo.yaml
    - name: Update image tag and env vars
      run: |
        # Get current production tag and increment it
        export CURRENT_TAG="$(python -m yq -r '.services[] | select(.name == "platform") | .image.tag' production.yaml)"
        export NEW_TAG="2.139.0"  # This should be determined by your versioning strategy
        echo "Updating production image tag from $CURRENT_TAG to $NEW_TAG"
        # Update tags
        python -m yq -Y --indentless --arg TAG "$NEW_TAG" '.services[].image.tag = $TAG' production.yaml > tmp.yaml && mv tmp.yaml production.yaml
        python -m yq -Y --indentless --arg TAG "$NEW_TAG" '.services[].image.tag = $TAG' demo.yaml > tmp.yaml && mv tmp.yaml demo.yaml
        # Add SERVICE_TYPE env var to worker services
        python -m yq -Y --indentless '.services[] | select(.name == "django-q-worker") | .envs += [{"key": "SERVICE_TYPE", "scope": "RUN_AND_BUILD_TIME", "value": "worker"}]' production.yaml > tmp.yaml && mv tmp.yaml production.yaml
        python -m yq -Y --indentless '.services[] | select(.name == "django-q-worker") | .envs += [{"key": "SERVICE_TYPE", "scope": "RUN_AND_BUILD_TIME", "value": "worker"}]' demo.yaml > tmp.yaml && mv tmp.yaml demo.yaml
    - name: Update the environments
      run: |
        doctl apps update $PRODUCTION_ID --spec production.yaml
        doctl apps update $DEMO_ID --spec demo.yaml
        
    - name: Wait for deployment
      run: sleep 30
      
    - name: Check production deployment
      run: |
        echo "Production worker logs:"
        doctl apps logs $PRODUCTION_ID component=django-q-worker --tail 50
        echo "Production platform logs:"
        doctl apps logs $PRODUCTION_ID component=platform --tail 50
        
    - name: Check demo deployment
      run: |
        echo "Demo worker logs:"
        doctl apps logs $DEMO_ID component=django-q-worker --tail 50
        echo "Demo platform logs:"
        doctl apps logs $DEMO_ID component=platform --tail 50